<?php


$form = $this->form;
//$form->setAttribute('action', $this->url('hello' ,array('action' => 'add')));
$form->setAttribute('action', $this->url('blog',array('action' => 'add'), TRUE));


$form->get('user_id')->setValueOptions($user);


$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('tag'));
echo $this->formRow($form->get('body'));
echo $this->formRow($form->get('user_id'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();