<?php 

$this->headLink()->appendStylesheet($this->basePath()."//js/jquery-ui/css/ui-lightness/jquery-ui-1.10.3.custom.min.css");
$this->headScript()->appendFile($this->basePath()."/js/jquery-ui/js/jquery-1.9.1.js");
$this->headScript()->appendFile($this->basePath()."/js/jquery-ui/js/jquery-ui-1.10.3.custom.js");
?>
<script type="text/javascript">

$(function(){


})

function goajax(){
	var unputbox = $("#ammount").val();
   $.ajax({
       url: "<?php echo $this->url('blog', array('action' => 'ajaxdata', 'id' => 100)) ?>" ,
       data: {firstvalue : unputbox},
       success: function(data){
       	$("#display").html(data);
       }

   });
}

</script>
<h1>Greetings!</h1>

<p>You said "<?php echo $this->escapeHtml($message) ?>".</p>


<input type="text" id="ammount">
<input type="button" onclick="goajax();" value="Try Ajax" /> 

<div  id="display"> </div>






