
<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
</noscript>
			
<div id="content" class="span10">
			<!-- content starts -->
		 <?php echo $this->flashMessenger()->render(); ?>
			<div>
				<ul class="breadcrumb">
					<li>
						<a href="<?php echo $this->basePath();?>/admin"><?php echo $this->translate('Home')?></a> <span class="divider">/</span>
					</li>
					<li>
						<a href="<?php echo $this->basePath();?>/admin/cms"><?php echo $this->translate('CMS Pages')?></a>
					</li>
				</ul>
			</div>

<div class="row-fluid">		
	<div class="box span12">
		<div class="box-header well" data-original-title>
			<h2><i class="icon-book"></i> <?php echo $this->translate('cms'); ?></h2>
			<div class="box-icon">
				<a href="<?php echo $this->basePath();?>/admin/createnewpage" class="btn btn-primary"><i class="icon-plus icon-white"></i></a>
			</div>
		</div>
		<div class="box-content">
			<table class="table table-striped table-bordered bootstrap-datatable datatable">
			  <thead>
				  <tr>
					  <th><?php echo $this->translate('title');?></th>
					  <th><?php echo $this->translate('url');?></th>
					  <th><?php echo $this->translate('language');?></th>
					  <th><?php echo $this->translate("Actions")?></th>
				  </tr>
			  </thead>   
			  <tbody>
			  	<?php foreach($cmsresult as $row): ?>
				<tr id="item_<?php echo $row->id;?>">
					<td><?php echo $row->title;?></td>
					<td><a href="#" target="_blank"><?php echo $row->slug;?></a></td>
					<td class="center"><?php echo $row->lang?> </td>
					<td class="center">
						<a class="btn btn-info" href="<?php echo $this->basePath(); ?>/admin/editcmspage/<?php echo $row->id;?>">
							<i class="icon-edit icon-white"></i>  
							<?php echo $this->translate('Edit') ?>           
						</a>
						<a class="btn btn-danger" href="<?php echo $this->basePath(); ?>/admin/deletepage/<?php echo $row->id;?>">
							<i class="icon-trash icon-white"></i> 
							<?php echo $this->translate('Delete')?>
						</a>
					</td>
				</tr>
				<?php endforeach; ?>
			  </tbody>
		  </table>            
		</div>
	</div><!--/span-->
</div><!--/row-->
</div><!--/content end -->