
<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>
			
<div id="content" class="span10">
			<!-- content starts -->
			 <?php echo $this->flashMessenger()->render(); ?>

			<div>
				<ul class="breadcrumb">
					<li>
						<a href="<?php echo $this->basePath();?>/admin"><?php echo $this->translate('Home')?></a> <span class="divider">/</span>
					</li>
					<li>
						<a href="<?php echo $this->basePath();?>/admin/users"><?php echo $this->translate('Users')?></a>
					</li>
				</ul>
			</div>

<div class="row-fluid">		
	<div class="box span12">
		<div class="box-header well" data-original-title>
			<h2><i class="icon-user"></i> <?php echo $this->translate('Add Users'); ?></h2>
			
		</div>
		<div class="box-content">
<?php


$form = $this->regform ;

$form->setAttribute('action',$this->url('admin',array('action','createuser'),true));
$form->setAttribute('class','form-horizontal');

$form->prepare();

echo $this->form()->openTag($form);

foreach ($form as $element) : ?>

<div class="control-group <?php if($this->formElementErrors($element)) 
                                echo "error" ?>">
    <label class="control-label"><?php echo $this->translate($element->getLabel()) ?></label>
    <div class="controls">
        <?php echo $this->formElement($element);
        if($this->formElementErrors($element)) ?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    </div>
</div>

<?php
endforeach;
?>
<?php echo $this->form()->closeTag($form);  ?>

<?php 

/*
echo $this->form()->openTag($form);
echo "<div clss='control-group'>";
echo $this->formRow($form->get('name'));
echo "</div>";
echo "<div clss='control-group'>";

echo $this->formRow($form->get('username'));
echo "</div>";
echo "<div clss='control-group'>";
echo $this->formRow($form->get('email'));
echo "</div>";
echo "<div clss='control-group'>";
echo $this->formRow($form->get('password'));
echo "</div>";
echo "<div clss='control-group'>";
echo $this->formRow($form->get('age'));
echo "</div>";
echo "<div clss='control-group'>";
echo $this->formRow($form->get('role'));
echo "</div>";
echo "<div clss='control-group'>";
echo $this->formRow($form->get('state'));
echo "</div>";
echo "<div clss='control-group'>";



// echo $this->formRow($form->get('extra')); For evant manager attach extra filed in onBootstrap method in module ;

echo $this->formRow($form->get('submit'));

 echo $this->form()->closeTag();*/


?>
</div>
</div><!--/span-->

</div><!--/row-->

</div><!--/row-->