
<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>
			
<div id="content" class="span10">
			<!-- content starts -->
			 <?php echo $this->flashMessenger()->render(); ?>

			<div>
				<ul class="breadcrumb">
					<li>
						<a href="<?php echo $this->basePath();?>/admin"><?php echo $this->translate('Home')?></a> <span class="divider">/</span>
					</li>
					<li>
						<a href="<?php echo $this->basePath(); ?>/admin/users"><?php echo $this->translate('Users')?></a>
					</li>
				</ul>
			</div>

<div class="row-fluid">		
	<div class="box span12">
		<div class="box-header well" data-original-title>
			<h2><i class="icon-user"></i><?php echo  $this->translate('users'); ?></h2>
			<div class="box-icon">
				<a href="<?php echo $this->basePath() ?>/admin/createuser" class="btn btn-primary"><i class="icon-plus icon-white"></i></a>
			</div>
		</div>
		<div class="box-content">
			<table class="table table-striped table-bordered bootstrap-datatable datatable">
			  <thead>
				  <tr>
					  <th><?php echo $this->translate('username');?></th>
					  <th><?php echo $this->translate('name');?></th>
					  <th><?php echo $this->translate('user_group');?></th>
					  <th><?php echo $this->translate('status');?></th>
					  <th><?php echo $this->translate('Actions')?></th>
				  </tr>
			  </thead>   
			  <tbody>
			  	<?php foreach($userresult as $row): ?>
				<tr>
					<td><a href="mailto:<?php echo $row->username;?>"><?php echo $row->username;?></a></td>
					<td class="center"><?php if ($row->name == false): ?>-<?php else: ?><?php echo $row->name;?><?php endif; ?></td>
					<td class="center"><?php echo $row->role;?></td>
					<td class="center">
						<a class="btn btn-info" href="<?php echo $this->basePath(); ?>/admin/edituser/<?php echo $row->id;?>">
							<i class="icon-edit icon-white"></i>  
							<?php echo $this->translate('Edit') ?>      
						</a>
						<a class="btn btn-danger" href="<?php echo $this->basePath() ?>/admin/deleteuser/<?php echo $row->id;?>">
							<i class="icon-trash icon-white"></i> 
							<?php echo $this->translate('Delete') ?>
						</a>
					</td>
					<td class="center"><span class="label label<?php echo ($row->state)?'-success':'';?>"><?php echo ($row->state)?'Active':'Deactive';?></span></td>
				</tr>
				<?php endforeach; ?>
			  </tbody>
		  </table>            
		</div>
	</div><!--/span-->

</div><!--/row-->

</div><!--/row-->